@host = http://localhost:3505
@appId = scrapper-api

###

GET {{host}}/projects
dapr-app-id: {{appId}}

###

POST {{host}}/projects
dapr-app-id: {{appId}}

{ "id": "1",
  "name": "test",
  "address": "xxx",
  "abi": "yyy" }

###

DELETE {{host}}/projects/1
dapr-app-id: {{appId}}

###

PUT {{host}}/projects/2
dapr-app-id: {{appId}}

{ "id": "1",
  "name": "test",
  "address": "xxx",
  "abi": "zzz" }

###

GET {{host}}/projects/1/versions
dapr-app-id: {{appId}}

###

POST {{host}}/projects/1/versions
dapr-app-id: {{appId}}

{
  "id": "v1"
}

###

DELETE  {{host}}/projects/1/versions/v1
dapr-app-id: {{appId}}

###

POST {{host}}/projects/1/versions/v1/start
dapr-app-id: {{appId}}


###
GET {{host}}/projects/1/versions/v1/state
dapr-app-id: {{appId}}
