@host = http://localhost:3505
@appId = scrapper-api

###

GET {{host}}/projects
dapr-app-id: {{appId}}




###

POST {{host}}/projects
dapr-app-id: {{appId}}

{ "id": "9",
  "name": "test",
  "address": "xxx",
  "abi": "yyy" }

###

DELETE {{host}}/projects/9
dapr-app-id: {{appId}}

###

PUT {{host}}/projects/9
dapr-app-id: {{appId}}

{ "id": "9",
  "name": "test",
  "address": "xxx",
  "abi": "zzz" }
