@host = http://localhost:3505
@appId = scrapper-api

###

GET {{host}}/projects
dapr-app-id: {{appId}}

###

POST {{host}}/projects
dapr-app-id: {{appId}}

{ "id": "3",
  "name": "test",
  "address": "xxx",
  "abi": "yyy" }
